apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engine-processor-23126
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/engine-processor-23126
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
